// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: model/pb/msg_body.proto

package pbmodel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// elementType说明
type ElementType int32

const (
	ElementType_ELEMENT_TYPE_UNKNOWN    ElementType = 0  // 默认未知
	ElementType_TEXT_ELEMENT            ElementType = 1  // 文本段
	ElementType_PIC_ELEMENT             ElementType = 2  // 图片段
	ElementType_FILE_ELEMENT            ElementType = 3  // 文件消息
	ElementType_PTT_ELEMENT             ElementType = 4  // 语音消息
	ElementType_VIDEO_ELEMENT           ElementType = 5  // 视频消息
	ElementType_FACE_ELEMENT            ElementType = 6  // QQ系统表情
	ElementType_REPLY_ELEMENT           ElementType = 7  // 引用
	ElementType_GRAY_TIP_ELEMENT        ElementType = 8  // 系统消息（灰字提示）
	ElementType_WALLET_ELEMENT          ElementType = 9  // 红包消息
	ElementType_ARK_ELEMENT             ElementType = 10 // 卡片消息
	ElementType_MARKET_FACE_ELEMENT     ElementType = 11 // 商城表情
	ElementType_MARKDOWN_ELEMENT        ElementType = 14 // markdown消息
	ElementType_XML_ELEMENT             ElementType = 16 // XML消息
	ElementType_INLINE_KEYBOARD_ELEMENT ElementType = 17 // markdown按钮消息
	ElementType_AV_RECORD_ELEMENT       ElementType = 21 // 通话消息
	ElementType_FACE_BUBBLE_ELEMENT     ElementType = 27 // 弹射表情包
	ElementType_SHARE_LOCATION_ELEMENT  ElementType = 28 // 位置共享
)

// Enum value maps for ElementType.
var (
	ElementType_name = map[int32]string{
		0:  "ELEMENT_TYPE_UNKNOWN",
		1:  "TEXT_ELEMENT",
		2:  "PIC_ELEMENT",
		3:  "FILE_ELEMENT",
		4:  "PTT_ELEMENT",
		5:  "VIDEO_ELEMENT",
		6:  "FACE_ELEMENT",
		7:  "REPLY_ELEMENT",
		8:  "GRAY_TIP_ELEMENT",
		9:  "WALLET_ELEMENT",
		10: "ARK_ELEMENT",
		11: "MARKET_FACE_ELEMENT",
		14: "MARKDOWN_ELEMENT",
		16: "XML_ELEMENT",
		17: "INLINE_KEYBOARD_ELEMENT",
		21: "AV_RECORD_ELEMENT",
		27: "FACE_BUBBLE_ELEMENT",
		28: "SHARE_LOCATION_ELEMENT",
	}
	ElementType_value = map[string]int32{
		"ELEMENT_TYPE_UNKNOWN":    0,
		"TEXT_ELEMENT":            1,
		"PIC_ELEMENT":             2,
		"FILE_ELEMENT":            3,
		"PTT_ELEMENT":             4,
		"VIDEO_ELEMENT":           5,
		"FACE_ELEMENT":            6,
		"REPLY_ELEMENT":           7,
		"GRAY_TIP_ELEMENT":        8,
		"WALLET_ELEMENT":          9,
		"ARK_ELEMENT":             10,
		"MARKET_FACE_ELEMENT":     11,
		"MARKDOWN_ELEMENT":        14,
		"XML_ELEMENT":             16,
		"INLINE_KEYBOARD_ELEMENT": 17,
		"AV_RECORD_ELEMENT":       21,
		"FACE_BUBBLE_ELEMENT":     27,
		"SHARE_LOCATION_ELEMENT":  28,
	}
)

func (x ElementType) Enum() *ElementType {
	p := new(ElementType)
	*p = x
	return p
}

func (x ElementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_pb_msg_body_proto_enumTypes[0].Descriptor()
}

func (ElementType) Type() protoreflect.EnumType {
	return &file_model_pb_msg_body_proto_enumTypes[0]
}

func (x ElementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementType.Descriptor instead.
func (ElementType) EnumDescriptor() ([]byte, []int) {
	return file_model_pb_msg_body_proto_rawDescGZIP(), []int{0}
}

// 顶层消息结构：一条消息中可以有多个消息段
// 类型为protobuf 或 protobuf array。一条消息中可以有多个消息段，按内容顺序，类似于富文本；部分类型中可嵌套
type MsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*MsgElem             `protobuf:"bytes,40800,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBody) Reset() {
	*x = MsgBody{}
	mi := &file_model_pb_msg_body_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody) ProtoMessage() {}

func (x *MsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_model_pb_msg_body_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody.ProtoReflect.Descriptor instead.
func (*MsgBody) Descriptor() ([]byte, []int) {
	return file_model_pb_msg_body_proto_rawDescGZIP(), []int{0}
}

func (x *MsgBody) GetElements() []*MsgElem {
	if x != nil {
		return x.Elements
	}
	return nil
}

// 消息段结构
type MsgElem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ChatType             int32                  `protobuf:"varint,40010,opt,name=chatType,proto3" json:"chatType,omitempty"`
	ElementID            int32                  `protobuf:"varint,45001,opt,name=elementID,proto3" json:"elementID,omitempty"` // 元素id，与msgid一样，具有唯一性
	ElementType          ElementType            `protobuf:"varint,45002,opt,name=elementType,proto3,enum=model.ElementType" json:"elementType,omitempty"`
	SubElementType       int32                  `protobuf:"varint,45003,opt,name=subElementType,proto3" json:"subElementType,omitempty"` // ？ 未确定
	MsgId                string                 `protobuf:"bytes,45004,opt,name=msgId,proto3" json:"msgId,omitempty"`                    // +faceType
	Content              string                 `protobuf:"bytes,45101,opt,name=content,proto3" json:"content,omitempty"`                // 文本消息。elementType=1
	Text                 string                 `protobuf:"bytes,45102,opt,name=text,proto3" json:"text,omitempty"`                      // 语音转文字。elementType=4
	FileName             string                 `protobuf:"bytes,45402,opt,name=fileName,proto3" json:"fileName,omitempty"`              // 文件名。elementType=3/4
	FilePath             string                 `protobuf:"bytes,45403,opt,name=filePath,proto3" json:"filePath,omitempty"`              // 文件路径。elementType=3/4
	FileSize             int32                  `protobuf:"varint,45405,opt,name=fileSize,proto3" json:"fileSize,omitempty"`             // 文件大小。elementType=3/4
	Md5HexStr            int32                  `protobuf:"varint,45406,opt,name=md5HexStr,proto3" json:"md5HexStr,omitempty"`           // 视频消息中对应videoMD5。elementType=3
	File10MMD5           []byte                 `protobuf:"bytes,45407,opt,name=file10MMD5,proto3" json:"file10MMD5,omitempty"`          // 未知。elementType=3/4
	FileSha              []byte                 `protobuf:"bytes,45408,opt,name=fileSha,proto3" json:"fileSha,omitempty"`                // 未知。elementType=3
	FileSha3             []byte                 `protobuf:"bytes,45409,opt,name=fileSha3,proto3" json:"fileSha3,omitempty"`              // 未知。elementType=
	VideoTime            int32                  `protobuf:"varint,45410,opt,name=videoTime,proto3" json:"videoTime,omitempty"`           // 视频时间。elementType=3/5
	ThumbWidth           int32                  `protobuf:"varint,45411,opt,name=thumbWidth,proto3" json:"thumbWidth,omitempty"`         // 预览封面宽度。elementType=5
	ThumbHeight          int32                  `protobuf:"varint,45412,opt,name=thumbHeight,proto3" json:"thumbHeight,omitempty"`       // 预览封面高度。elementType=5
	PicWidth             int32                  `protobuf:"varint,45413,opt,name=picWidth,proto3" json:"picWidth,omitempty"`             // 原图宽度
	PicHeight            int32                  `protobuf:"varint,45414,opt,name=picHeight,proto3" json:"picHeight,omitempty"`           // 原图高度
	ThumbSize            int32                  `protobuf:"varint,45415,opt,name=thumbSize,proto3" json:"thumbSize,omitempty"`           // 预览封面大小。elementType=5
	PicType              int32                  `protobuf:"varint,45416,opt,name=picType,proto3" json:"picType,omitempty"`               // 图片类型，1000为静态图片，2000为gif。elementType=2
	Original             int32                  `protobuf:"varint,45418,opt,name=original,proto3" json:"original,omitempty"`
	ThumbFilename        string                 `protobuf:"bytes,45422,opt,name=thumbFilename,proto3" json:"thumbFilename,omitempty"` //（非官方）预览封面路径位于半私有目录/Tencent/MobileQQ/shortvideo/thumbs/。elementType=5
	OriginImageMd5       []byte                 `protobuf:"bytes,45424,opt,name=originImageMd5,proto3" json:"originImageMd5,omitempty"`
	FileUuid             string                 `protobuf:"bytes,45503,opt,name=fileUuid,proto3" json:"fileUuid,omitempty"`
	ThumbMD5             []byte                 `protobuf:"bytes,45862,opt,name=thumbMD5,proto3" json:"thumbMD5,omitempty"`                          // 预览封面MD5(对于45422文件)。elementType=5
	Duration             int32                  `protobuf:"varint,45906,opt,name=duration,proto3" json:"duration,omitempty"`                         // 语音持续时间。elementType=4
	VoiceText            string                 `protobuf:"bytes,45923,opt,name=voiceText,proto3" json:"voiceText,omitempty"`                        // 语音转文字。elementType=4
	WaveAmplitudes       []byte                 `protobuf:"bytes,45925,opt,name=waveAmplitudes,proto3" json:"waveAmplitudes,omitempty"`              // 信号频率。elementType=4
	PicThumbPath         string                 `protobuf:"bytes,45954,opt,name=picThumbPath,proto3" json:"picThumbPath,omitempty"`                  // 预览封面路径。elementType=3
	ReplyMsgId           int32                  `protobuf:"varint,47401,opt,name=replyMsgId,proto3" json:"replyMsgId,omitempty"`                     // 引用的消息msgid。elementType=7
	ReplyMsgSeq          int32                  `protobuf:"varint,47402,opt,name=replyMsgSeq,proto3" json:"replyMsgSeq,omitempty"`                   // 引用的消息seq。elementType=7
	ReplyMsgTime1        int32                  `protobuf:"varint,47403,opt,name=replyMsgTime1,proto3" json:"replyMsgTime1,omitempty"`               // 引用的消息发送时间戳。elementType=7
	ReplyMsgTime2        int32                  `protobuf:"varint,47404,opt,name=replyMsgTime2,proto3" json:"replyMsgTime2,omitempty"`               // 引用的消息发送时间戳。elementType=7
	ReplyContent         string                 `protobuf:"bytes,47413,opt,name=replyContent,proto3" json:"replyContent,omitempty"`                  // 引用的消息，仅文本。elementType=7
	ReplySenderNickname  string                 `protobuf:"bytes,47421,opt,name=replySenderNickname,proto3" json:"replySenderNickname,omitempty"`    // 引用放群昵称。elementType=7
	SourceMsgIdInRecords int32                  `protobuf:"varint,47422,opt,name=sourceMsgIdInRecords,proto3" json:"sourceMsgIdInRecords,omitempty"` // 未知。elementType=7
	FaceIndex            int32                  `protobuf:"varint,47601,opt,name=faceIndex,proto3" json:"faceIndex,omitempty"`                       // 表情id。elementType=6
	FaceText             string                 `protobuf:"bytes,47602,opt,name=faceText,proto3" json:"faceText,omitempty"`                          // 表情含义（外显文字）
	BytesData            string                 `protobuf:"bytes,47901,opt,name=bytesData,proto3" json:"bytesData,omitempty"`                        // 卡片详细信息
	MsgTime              int32                  `protobuf:"varint,49155,opt,name=msgTime,proto3" json:"msgTime,omitempty"`                           // 发送时间
	ThumbSiz             int32                  `protobuf:"varint,95654,opt,name=thumbSiz,proto3" json:"thumbSiz,omitempty"`                         // 预览封面大小。elementType=3
	RecallSuffix         string                 `protobuf:"bytes,47713,opt,name=recallSuffix,proto3" json:"recallSuffix,omitempty"`                  // 撤回消息后缀，适用于系统撤回消息
	XmlContent           string                 `protobuf:"bytes,48602,opt,name=xmlContent,proto3" json:"xmlContent,omitempty"`                      // xml消息内容。elementType=16
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MsgElem) Reset() {
	*x = MsgElem{}
	mi := &file_model_pb_msg_body_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgElem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgElem) ProtoMessage() {}

func (x *MsgElem) ProtoReflect() protoreflect.Message {
	mi := &file_model_pb_msg_body_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgElem.ProtoReflect.Descriptor instead.
func (*MsgElem) Descriptor() ([]byte, []int) {
	return file_model_pb_msg_body_proto_rawDescGZIP(), []int{1}
}

func (x *MsgElem) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *MsgElem) GetElementID() int32 {
	if x != nil {
		return x.ElementID
	}
	return 0
}

func (x *MsgElem) GetElementType() ElementType {
	if x != nil {
		return x.ElementType
	}
	return ElementType_ELEMENT_TYPE_UNKNOWN
}

func (x *MsgElem) GetSubElementType() int32 {
	if x != nil {
		return x.SubElementType
	}
	return 0
}

func (x *MsgElem) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *MsgElem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MsgElem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MsgElem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MsgElem) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *MsgElem) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MsgElem) GetMd5HexStr() int32 {
	if x != nil {
		return x.Md5HexStr
	}
	return 0
}

func (x *MsgElem) GetFile10MMD5() []byte {
	if x != nil {
		return x.File10MMD5
	}
	return nil
}

func (x *MsgElem) GetFileSha() []byte {
	if x != nil {
		return x.FileSha
	}
	return nil
}

func (x *MsgElem) GetFileSha3() []byte {
	if x != nil {
		return x.FileSha3
	}
	return nil
}

func (x *MsgElem) GetVideoTime() int32 {
	if x != nil {
		return x.VideoTime
	}
	return 0
}

func (x *MsgElem) GetThumbWidth() int32 {
	if x != nil {
		return x.ThumbWidth
	}
	return 0
}

func (x *MsgElem) GetThumbHeight() int32 {
	if x != nil {
		return x.ThumbHeight
	}
	return 0
}

func (x *MsgElem) GetPicWidth() int32 {
	if x != nil {
		return x.PicWidth
	}
	return 0
}

func (x *MsgElem) GetPicHeight() int32 {
	if x != nil {
		return x.PicHeight
	}
	return 0
}

func (x *MsgElem) GetThumbSize() int32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *MsgElem) GetPicType() int32 {
	if x != nil {
		return x.PicType
	}
	return 0
}

func (x *MsgElem) GetOriginal() int32 {
	if x != nil {
		return x.Original
	}
	return 0
}

func (x *MsgElem) GetThumbFilename() string {
	if x != nil {
		return x.ThumbFilename
	}
	return ""
}

func (x *MsgElem) GetOriginImageMd5() []byte {
	if x != nil {
		return x.OriginImageMd5
	}
	return nil
}

func (x *MsgElem) GetFileUuid() string {
	if x != nil {
		return x.FileUuid
	}
	return ""
}

func (x *MsgElem) GetThumbMD5() []byte {
	if x != nil {
		return x.ThumbMD5
	}
	return nil
}

func (x *MsgElem) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MsgElem) GetVoiceText() string {
	if x != nil {
		return x.VoiceText
	}
	return ""
}

func (x *MsgElem) GetWaveAmplitudes() []byte {
	if x != nil {
		return x.WaveAmplitudes
	}
	return nil
}

func (x *MsgElem) GetPicThumbPath() string {
	if x != nil {
		return x.PicThumbPath
	}
	return ""
}

func (x *MsgElem) GetReplyMsgId() int32 {
	if x != nil {
		return x.ReplyMsgId
	}
	return 0
}

func (x *MsgElem) GetReplyMsgSeq() int32 {
	if x != nil {
		return x.ReplyMsgSeq
	}
	return 0
}

func (x *MsgElem) GetReplyMsgTime1() int32 {
	if x != nil {
		return x.ReplyMsgTime1
	}
	return 0
}

func (x *MsgElem) GetReplyMsgTime2() int32 {
	if x != nil {
		return x.ReplyMsgTime2
	}
	return 0
}

func (x *MsgElem) GetReplyContent() string {
	if x != nil {
		return x.ReplyContent
	}
	return ""
}

func (x *MsgElem) GetReplySenderNickname() string {
	if x != nil {
		return x.ReplySenderNickname
	}
	return ""
}

func (x *MsgElem) GetSourceMsgIdInRecords() int32 {
	if x != nil {
		return x.SourceMsgIdInRecords
	}
	return 0
}

func (x *MsgElem) GetFaceIndex() int32 {
	if x != nil {
		return x.FaceIndex
	}
	return 0
}

func (x *MsgElem) GetFaceText() string {
	if x != nil {
		return x.FaceText
	}
	return ""
}

func (x *MsgElem) GetBytesData() string {
	if x != nil {
		return x.BytesData
	}
	return ""
}

func (x *MsgElem) GetMsgTime() int32 {
	if x != nil {
		return x.MsgTime
	}
	return 0
}

func (x *MsgElem) GetThumbSiz() int32 {
	if x != nil {
		return x.ThumbSiz
	}
	return 0
}

func (x *MsgElem) GetRecallSuffix() string {
	if x != nil {
		return x.RecallSuffix
	}
	return ""
}

func (x *MsgElem) GetXmlContent() string {
	if x != nil {
		return x.XmlContent
	}
	return ""
}

var File_model_pb_msg_body_proto protoreflect.FileDescriptor

const file_model_pb_msg_body_proto_rawDesc = "" +
	"\n" +
	"\x17model/pb/msg_body.proto\x12\x05model\"7\n" +
	"\aMsgBody\x12,\n" +
	"\belements\x18\xe0\xbe\x02 \x03(\v2\x0e.model.MsgElemR\belements\"\xe9\v\n" +
	"\aMsgElem\x12\x1c\n" +
	"\bchatType\x18ʸ\x02 \x01(\x05R\bchatType\x12\x1e\n" +
	"\telementID\x18\xc9\xdf\x02 \x01(\x05R\telementID\x126\n" +
	"\velementType\x18\xca\xdf\x02 \x01(\x0e2\x12.model.ElementTypeR\velementType\x12(\n" +
	"\x0esubElementType\x18\xcb\xdf\x02 \x01(\x05R\x0esubElementType\x12\x16\n" +
	"\x05msgId\x18\xcc\xdf\x02 \x01(\tR\x05msgId\x12\x1a\n" +
	"\acontent\x18\xad\xe0\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x04text\x18\xae\xe0\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\bfileName\x18\xda\xe2\x02 \x01(\tR\bfileName\x12\x1c\n" +
	"\bfilePath\x18\xdb\xe2\x02 \x01(\tR\bfilePath\x12\x1c\n" +
	"\bfileSize\x18\xdd\xe2\x02 \x01(\x05R\bfileSize\x12\x1e\n" +
	"\tmd5HexStr\x18\xde\xe2\x02 \x01(\x05R\tmd5HexStr\x12 \n" +
	"\n" +
	"file10MMD5\x18\xdf\xe2\x02 \x01(\fR\n" +
	"file10MMD5\x12\x1a\n" +
	"\afileSha\x18\xe0\xe2\x02 \x01(\fR\afileSha\x12\x1c\n" +
	"\bfileSha3\x18\xe1\xe2\x02 \x01(\fR\bfileSha3\x12\x1e\n" +
	"\tvideoTime\x18\xe2\xe2\x02 \x01(\x05R\tvideoTime\x12 \n" +
	"\n" +
	"thumbWidth\x18\xe3\xe2\x02 \x01(\x05R\n" +
	"thumbWidth\x12\"\n" +
	"\vthumbHeight\x18\xe4\xe2\x02 \x01(\x05R\vthumbHeight\x12\x1c\n" +
	"\bpicWidth\x18\xe5\xe2\x02 \x01(\x05R\bpicWidth\x12\x1e\n" +
	"\tpicHeight\x18\xe6\xe2\x02 \x01(\x05R\tpicHeight\x12\x1e\n" +
	"\tthumbSize\x18\xe7\xe2\x02 \x01(\x05R\tthumbSize\x12\x1a\n" +
	"\apicType\x18\xe8\xe2\x02 \x01(\x05R\apicType\x12\x1c\n" +
	"\boriginal\x18\xea\xe2\x02 \x01(\x05R\boriginal\x12&\n" +
	"\rthumbFilename\x18\xee\xe2\x02 \x01(\tR\rthumbFilename\x12(\n" +
	"\x0eoriginImageMd5\x18\xf0\xe2\x02 \x01(\fR\x0eoriginImageMd5\x12\x1c\n" +
	"\bfileUuid\x18\xbf\xe3\x02 \x01(\tR\bfileUuid\x12\x1c\n" +
	"\bthumbMD5\x18\xa6\xe6\x02 \x01(\fR\bthumbMD5\x12\x1c\n" +
	"\bduration\x18\xd2\xe6\x02 \x01(\x05R\bduration\x12\x1e\n" +
	"\tvoiceText\x18\xe3\xe6\x02 \x01(\tR\tvoiceText\x12(\n" +
	"\x0ewaveAmplitudes\x18\xe5\xe6\x02 \x01(\fR\x0ewaveAmplitudes\x12$\n" +
	"\fpicThumbPath\x18\x82\xe7\x02 \x01(\tR\fpicThumbPath\x12 \n" +
	"\n" +
	"replyMsgId\x18\xa9\xf2\x02 \x01(\x05R\n" +
	"replyMsgId\x12\"\n" +
	"\vreplyMsgSeq\x18\xaa\xf2\x02 \x01(\x05R\vreplyMsgSeq\x12&\n" +
	"\rreplyMsgTime1\x18\xab\xf2\x02 \x01(\x05R\rreplyMsgTime1\x12&\n" +
	"\rreplyMsgTime2\x18\xac\xf2\x02 \x01(\x05R\rreplyMsgTime2\x12$\n" +
	"\freplyContent\x18\xb5\xf2\x02 \x01(\tR\freplyContent\x122\n" +
	"\x13replySenderNickname\x18\xbd\xf2\x02 \x01(\tR\x13replySenderNickname\x124\n" +
	"\x14sourceMsgIdInRecords\x18\xbe\xf2\x02 \x01(\x05R\x14sourceMsgIdInRecords\x12\x1e\n" +
	"\tfaceIndex\x18\xf1\xf3\x02 \x01(\x05R\tfaceIndex\x12\x1c\n" +
	"\bfaceText\x18\xf2\xf3\x02 \x01(\tR\bfaceText\x12\x1e\n" +
	"\tbytesData\x18\x9d\xf6\x02 \x01(\tR\tbytesData\x12\x1a\n" +
	"\amsgTime\x18\x83\x80\x03 \x01(\x05R\amsgTime\x12\x1c\n" +
	"\bthumbSiz\x18\xa6\xeb\x05 \x01(\x05R\bthumbSiz\x12$\n" +
	"\frecallSuffix\x18\xe1\xf4\x02 \x01(\tR\frecallSuffix\x12 \n" +
	"\n" +
	"xmlContent\x18\xda\xfb\x02 \x01(\tR\n" +
	"xmlContent*\x89\x03\n" +
	"\vElementType\x12\x18\n" +
	"\x14ELEMENT_TYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fTEXT_ELEMENT\x10\x01\x12\x0f\n" +
	"\vPIC_ELEMENT\x10\x02\x12\x10\n" +
	"\fFILE_ELEMENT\x10\x03\x12\x0f\n" +
	"\vPTT_ELEMENT\x10\x04\x12\x11\n" +
	"\rVIDEO_ELEMENT\x10\x05\x12\x10\n" +
	"\fFACE_ELEMENT\x10\x06\x12\x11\n" +
	"\rREPLY_ELEMENT\x10\a\x12\x14\n" +
	"\x10GRAY_TIP_ELEMENT\x10\b\x12\x12\n" +
	"\x0eWALLET_ELEMENT\x10\t\x12\x0f\n" +
	"\vARK_ELEMENT\x10\n" +
	"\x12\x17\n" +
	"\x13MARKET_FACE_ELEMENT\x10\v\x12\x14\n" +
	"\x10MARKDOWN_ELEMENT\x10\x0e\x12\x0f\n" +
	"\vXML_ELEMENT\x10\x10\x12\x1b\n" +
	"\x17INLINE_KEYBOARD_ELEMENT\x10\x11\x12\x15\n" +
	"\x11AV_RECORD_ELEMENT\x10\x15\x12\x17\n" +
	"\x13FACE_BUBBLE_ELEMENT\x10\x1b\x12\x1a\n" +
	"\x16SHARE_LOCATION_ELEMENT\x10\x1cB\vZ\t./pbmodelb\x06proto3"

var (
	file_model_pb_msg_body_proto_rawDescOnce sync.Once
	file_model_pb_msg_body_proto_rawDescData []byte
)

func file_model_pb_msg_body_proto_rawDescGZIP() []byte {
	file_model_pb_msg_body_proto_rawDescOnce.Do(func() {
		file_model_pb_msg_body_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_pb_msg_body_proto_rawDesc), len(file_model_pb_msg_body_proto_rawDesc)))
	})
	return file_model_pb_msg_body_proto_rawDescData
}

var file_model_pb_msg_body_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_model_pb_msg_body_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_pb_msg_body_proto_goTypes = []any{
	(ElementType)(0), // 0: model.ElementType
	(*MsgBody)(nil),  // 1: model.MsgBody
	(*MsgElem)(nil),  // 2: model.MsgElem
}
var file_model_pb_msg_body_proto_depIdxs = []int32{
	2, // 0: model.MsgBody.elements:type_name -> model.MsgElem
	0, // 1: model.MsgElem.elementType:type_name -> model.ElementType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_model_pb_msg_body_proto_init() }
func file_model_pb_msg_body_proto_init() {
	if File_model_pb_msg_body_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_pb_msg_body_proto_rawDesc), len(file_model_pb_msg_body_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_pb_msg_body_proto_goTypes,
		DependencyIndexes: file_model_pb_msg_body_proto_depIdxs,
		EnumInfos:         file_model_pb_msg_body_proto_enumTypes,
		MessageInfos:      file_model_pb_msg_body_proto_msgTypes,
	}.Build()
	File_model_pb_msg_body_proto = out.File
	file_model_pb_msg_body_proto_goTypes = nil
	file_model_pb_msg_body_proto_depIdxs = nil
}
